repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
    -   id: ruff
        args: ["--config", "pyproject.toml", "--fix", "--exit-non-zero-on-fix"]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
